[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "relocation-model=static",
  "-C", "link-arg=-nostdlib",
  "-C", "link-arg=-static",
  "-C", "link-arg=-Wl,--build-id=none",
  "-C", "link-arg=-Wl,-Tlinker.ld",
]

